#!/bin/bash

export AZQFLAGS="-I$AZQROOT/pmi -I$AZQROOT/pmi/simple -I$AZQROOT/arch/include -I$AZQROOT/idsp/blk/impl -I$AZQROOT/idsp/blk/spec -I$AZQROOT/inet -I$AZQROOT/inet/none/spec -I$AZQROOT/inet/none/impl -I/usr/local/include -I$AZQROOT/azqmpi/include -I$AZQROOT/config"
export KLEECFLAGS="-I$KLEEROOT/include"

exec "clang" -std=c89 -c -g -emit-llvm $AZQFLAGS $KLEECFLAGS -include hook.h $*